apiVersion: v1
kind: Service
metadata:
  name: friend-service
spec:
  selector:
    app: friend-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP  # Use LoadBalancer for external access, if needed
